### ISSUE TITLE
Vorschläge zur Verbesserung

### ISSUE THREAD

**Issue by AlCalzone** [UncleSamSwiss/iobroker-dev-portal#1]
- [ ] Klick auf Adapter Check macht nichts. Sollte bestenfalls zum Login führen wenn man noch nicht eingeloggt ist
- [ ] Dokumentation finde ich wichtiger als Comminuty-Initiativen, das sollte bestenfalls ganz vorne stehen.

**Comment by UncleSamSwiss** [comment]
Wegen Design-Problemen mit den MUI Card (Alignment zwischen den Cards stimmte nicht mehr) musste ich das klicken auf eine Karte ganz wegnehmen. Nun gibt es überall immer Buttons.
