### ISSUE TITLE
Add link to Sentry

### ISSUE THREAD

**Issue by UncleSamSwiss** [UncleSamSwiss/iobroker-dev-portal#10]
If possible, it would be nice to have on the adapter cards a direct link to the Sentry project dashboard if Sentry is enabled in an adapter.

**Comment by Apollon77** [comment]
Also add an info link that points tio the sentry plugin with "what is it and what do I need to do" link

**Comment by UncleSamSwiss** [comment]
This is now implemented. The documentation about Sentry will come at a later date (together with more detailed Sentry statistics on the adapter details page).
