### ISSUE TITLE
Add link to adapter community

### ISSUE THREAD

**Issue by Apollon77** [UncleSamSwiss/iobroker-dev-portal#11]
to github info page

**Comment by UncleSamSwiss** [comment]
Isn't community adapters more for adapters that have no longer a "real home"? So not really a resource for developers, but rather a collection of adapters. I wouldn't like to add all kinds of links but just the most important, so (new) developers can quickly find their way around adapter development.

**Comment by Apollon77** [comment]
ok, ack
