### ISSUE TITLE
Creator: Generating Adapter (download ZIP) gives no feedback

### ISSUE THREAD

**Issue by AlCalzone** [UncleSamSwiss/iobroker-dev-portal#20]
You can't see if anything is going on, nor can you do anything here.
![grafik](https://user-images.githubusercontent.com/17641229/114568102-2375e380-9c74-11eb-9e0f-b2235675673b.png)

**Comment by UncleSamSwiss** [comment]
This seems to be a bug.
Can you describe how you ended up with this empty screen?

**Comment by AlCalzone** [comment]
I filled out the adapter creation wizard and clicked on "download ZIP"

**Comment by UncleSamSwiss** [comment]
Fixed.
